package com.example.interviewtask.models


data class ImageX(
    val accountId: Any,
    val accountUrl: Any,
    val adType: Int,
    val adUrl: String,
    val animated: Boolean,
    val bandwidth: Long,
    val commentCount: Any,
    val datetime: Int,
    val description: String,
    val downs: Any,
    val edited: String,
    val favorite: Boolean,
    val favoriteCount: Any,
    val gifv: String,
    val hasSound: Boolean,
    val height: Int,
    val hls: String,
    val id: String,
    val inGallery: Boolean,
    val inMostViral: Boolean,
    val isAd: Boolean,
    val link: String,
    val mp4: String,
    val mp4Size: Int,
    val nsfw: Any,
    val points: Any,
    val processing: Processing,
    val score: Any,
    val section: Any,
    val size: Int,
    val tags: List<Any>,
    val title: Any,
    val type: String,
    val ups: Any,
    val views: Int,
    val vote: Any,
    val width: Int
)