package com.example.interviewtask.models.ImageModel

import java.io.Serializable


data class ViralImage(
    val data: List<DataImage>,
    val status: Int,
    val success: Boolean
): Serializable

data class DataImage(
    val accountId: Int,
    val accountUrl: String,
//    val adConfig: AdConfig,
    val adType: Int,
    val adUrl: String,
    val commentCount: Int,
    val cover: String,
    val coverHeight: Int,
    val coverWidth: Int,
    val datetime: Int,
    val description: String,
    val downs: Int,
    val favorite: Boolean,
    val favoriteCount: Int,
    val id: String,
    val images: List<ImageXX>?,
    val imagesCount: Int,
    val inGallery: Boolean,
    val inMostViral: Boolean,
    val includeAlbumAds: Boolean,
    val isAd: Boolean,
    val isAlbum: Boolean,
    val layout: String,
    val link: String,
    val nsfw: Boolean,
    val points: Int,
    val privacy: String,
    val score: Int,
    val section: String,
    val tags: List<Tag>,
    val title: String,
    val topic: Any,
    val topicId: Any,
    val ups: Int,
    val views: Int,
    val vote: Any
): Serializable

data class ImageXX(
    val accountId: String,
    val accountUrl: String,
    val adType: Int,
    val adUrl: String,
    val animated: Boolean,
    val bandwidth: Long,
    val commentCount: String,
    val datetime: Int,
    val description: String,
    val downs: String,
    val edited: String,
    val favorite: Boolean,
    val favoriteCount: String,
    val gifv: String,
    val hasSound: Boolean,
    val height: Int,
    val hls: String,
    val id: String,
    val inGallery: Boolean,
    val inMostViral: Boolean,
    val isAd: Boolean,
    val link: String,
    val mp4: String,
    val mp4Size: Int,
    val nsfw: String,
    val points: String,
    val score: String,
    val section: String,
    val size: Int,
    val tags: List<String>,
    val title: String,
    val type: String,
    val ups: String,
    val views: Int,
    val vote: String,
    val width: Int
): Serializable